### ISSUE TITLE
creating branches

### ISSUE THREAD

**Issue by toedtli** [TheSoundOfAIOSR/rg_text_to_sound#1]
As a contributor, I currently can't create branches and push to them. So how can I contribute code?

$ git branch
  main
* toedtli_textembeddings

$ git push --set-upstream origin toedtli_textembeddings
remote: Permission to TheSoundOfAIOSR/rg_text_to_sound.git denied to toedtli.
fatal: unable to access 'https://github.com/TheSoundOfAIOSR/rg_text_to_sound.git/': The requested URL returned error: 403

**Comment by wassfila** [comment]
Zou did not accept the invite to join the group
![image](https://user-images.githubusercontent.com/1510763/107795167-a0f6a380-6d58-11eb-8646-1ff92a12c8ea.png)
